import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "田前秀樹",
  alternateName: "Hideki Tamae",
  jobTitle: "Civilizational OS Designer / AI Architect",
  worksFor: {
    "@type": "Organization",
    name: "Tech Noir Labs",
  },
  url: "https://tech-noir-labs.vercel.app",
  sameAs: [
    "https://author.amazon.co.jp/profile",
    "https://github.com/hideki-tamae",
  ],
  knowsAbout: [
    "AI Agents",
    "Harness/Loop Engineering",
    "Care Capitalism",
    "Web3",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(personJsonLd),
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
